djangonautic/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup_view,name="signup"),
    path('login/',views.login_view,name="login"),
    path('logout/',views.logout_view,name="logout"),
]

djangonautic/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('', views.home, name="list"),
    path('create/', views.article_create, name="create"),
    path('<slug>/', views.article_detail, name="detail"),
]

djangonautic/djangonautic/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from djangonautic import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', views.home)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangonautic/accounts/models.py
from django.db import models

# Create your models here.

djangonautic/articles/models.py
from django.db import models
from django.contrib.auth.models import User

class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.jpg')
    author = models.ForeignKey(User, default=None,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return (self.body[:50])

djangonautic/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title','body','slug','thumb']

djangonautic/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login,logout

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save();
            login(request,user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html', {'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html', {'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

djangonautic/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

def home(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles_list.html', {'articles': articles})

def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request,'article_detail.html', {'article':article})

@login_required(login_url='/accounts/login/')
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit=False);
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request,'article_create.html',{'form':form})

djangonautic/djangonautic/views.py
from django.shortcuts import render

def home(request):
    return  render(request, 'home.html')

djangonautic/accounts/templates/accounts/login.html
{%extends 'base_layout.html'%}

{% block content %}
<h1>Log In</h1>
<form class="site-form" action="{% url 'accounts:login' %}" method="post">
  {% csrf_token %}
  {{ form }}
  {% if request.GET.next %}
    <input type="hidden" name="next" value="{{request.GET.next}}">
  {%endif%}
  <input type="submit" value="Login">
</form>
{%endblock%}

djangonautic/accounts/templates/accounts/signup.html
{%extends 'base_layout.html'%}

{% block content %}
<h1>Signup</h1>
<form class="site-form" action="{% url 'accounts:signup' %}" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Signup">
</form>
{%endblock%}

djangonautic/articles/templates/article_create.html
{%extends 'base_layout.html'%}

{%block content%}
  <div class="create-article">
    <h2>Create!</h2>
    <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="Create">
    </form>
  </div>
{%endblock%}

djangonautic/articles/templates/article_detail.html
{%extends 'base_layout.html'%}

{%block content%}
<div class="aricle-detail">
  <div class="article">
    <h2>{{article.title}}</h2>
    <img src="{{article.thumb.url}}" alt="photo">
    <p>{{article.body}}</p>
    <p>created by: {{article.author}}</p>
    <p>{{article.date}}</p>
  </div>
</div>
{%endblock%}

djangonautic/articles/templates/articles_list.html
{%extends 'base_layout.html'%}

{%block content%}
<h1>Articles</h1>
<div class="articles">
  {% for article in articles %}
  <div class="article">
    <h2><a href="{% url 'articles:detail' slug=article.slug%}">{{article.title}}</a></h2>
    <p>{{article.snippet}}...</p>
    <p>{{article.date}}</p>
  </div>
  {% endfor %}
</div>
{%endblock%}

djangonautic/templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Ubuntu" />
    <link rel="stylesheet" href="{%static 'stayle.css'%}">
  </head>
  <body>
    <div class="warapper">
      <h1><a href="{% url 'articles:list' %}"><img src="{% static 'logo.jpg'%}" alt="logo"></a></h1>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li>
            <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
              {%csrf_token%}
              <button type="submit" name="logout">Log Out</button>
            </form>
          </li>
          {%else%}
          <li>
            <a href="{% url 'accounts:login' %}">Login</a>
          </li>
          <li>
            <a href="{% url 'accounts:signup' %}">Signup</a>
          </li>
          {%endif%}
        </ul>
      </nav>
      {%block content%}
      {%endblock%}
    </div>
  </body>
</html>

djangonautic/templates/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Home</h1>
    <p>
      in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus
      dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum
      ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien
      urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue
      etiam justo etiam pretium
    </p>
  </body>
</html>